// Cache-first for the app shell so an installed Hearth & Bench opens offline.
// index.html is generated by web/build_src/build.py — every screen is
// already in it, so there is only one page plus its runtime to cache.
const CACHE = 'shb-v2';
const SHELL = [
  './',
  './index.html',
  './icon.svg',
  './manifest.webmanifest',
  './src/styles/tokens.css',
  './src/styles/base.css',
  './src/styles/components.css',
  './src/app.js',
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  e.respondWith(
    caches.match(e.request).then((hit) => hit ?? fetch(e.request)),
  );
});
