// Cache-first for the app shell so an installed Summit Basecamp opens offline.
// index.html is generated by web/build_src/build.py — every screen is
// already in it, so there is only one page plus its runtime to cache.
const CACHE = 'shb-v2';
const SHELL = [
  './',
  './index.html',
  './icon.svg',
  './manifest.webmanifest',
  './src/styles/tokens.css',
  './src/styles/base.css',
  './src/styles/components.css',
  './src/app.js',
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  // Stale-while-revalidate: answer from cache immediately when there's a
  // hit (fast, works offline), but always refetch in the background and
  // update the cache, so a new deploy is picked up on the next load without
  // depending on someone remembering to bump CACHE.
  e.respondWith(
    caches.open(CACHE).then((cache) => cache.match(e.request).then((hit) => {
      const network = fetch(e.request).then((res) => {
        if (res.ok) cache.put(e.request, res.clone());
        return res;
      }).catch(() => hit);
      return hit ?? network;
    })),
  );
});
