// Network-first for the app shell, so an installed Summit Basecamp always
// runs the latest deploy while online and only falls back to the cache
// offline. index.html is generated by web/build_src/build.py — every
// screen is already in it, so there is only one page plus its runtime to
// cache.
const CACHE = 'basecamp-v2';
const SHELL = [
  './',
  './index.html',
  './icon.svg',
  './manifest.webmanifest',
  './src/styles/tokens.css',
  './src/styles/base.css',
  './src/styles/components.css',
  './src/app.js',
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  // Only the app shell itself is this service worker's job -- cross-origin
  // API calls (summit-basecamp-api.shb-fe7.workers.dev) must never be
  // shadowed through here. Left unscoped, every GET, auth'd API responses
  // included, would get sent through this fetch/cache dance too: cached
  // into this origin's Cache Storage (where any script on the page can
  // read it back, unlike an ordinary in-memory fetch response) and
  // potentially replayed stale from here if the real request ever failed,
  // instead of the caller just seeing that failure.
  if (new URL(e.request.url).origin !== self.location.origin) return;
  // Network-first: always try the network so a new deploy is visible on the
  // very next load, and only serve the cached shell when the network is
  // unreachable (offline). Stale-while-revalidate used to answer from
  // whatever was cached *before* checking the network, which meant every
  // visit rendered the previous deploy first -- a real fix on main could
  // sit invisible behind an already-installed service worker indefinitely.
  e.respondWith(
    fetch(e.request).then((res) => {
      if (res.ok) caches.open(CACHE).then((cache) => cache.put(e.request, res.clone()));
      return res;
    }).catch(() => caches.open(CACHE).then((cache) => cache.match(e.request))),
  );
});
